// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArf55bu0vRSMIBbpn5J8fQWMav-9SFh9U',
    appId: '1:351592381319:web:74956bb538f80ea949f122',
    messagingSenderId: '351592381319',
    projectId: 'realtime-database-crud-4b68b',
    authDomain: 'realtime-database-crud-4b68b.firebaseapp.com',
    databaseURL: 'https://realtime-database-crud-4b68b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-crud-4b68b.appspot.com',
    measurementId: 'G-4KXEFDM1NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVOB3tSVlrUu8WcVi567RRlUv_9qfkkp4',
    appId: '1:351592381319:android:c20b3b5dbd9a7b9949f122',
    messagingSenderId: '351592381319',
    projectId: 'realtime-database-crud-4b68b',
    databaseURL: 'https://realtime-database-crud-4b68b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-crud-4b68b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTrXIy-0RcK2izxy1dp37MI6VR6OLp3Xg',
    appId: '1:351592381319:ios:22b14366c27fe53649f122',
    messagingSenderId: '351592381319',
    projectId: 'realtime-database-crud-4b68b',
    databaseURL: 'https://realtime-database-crud-4b68b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-crud-4b68b.appspot.com',
    iosBundleId: 'com.example.firebaseRealdatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTrXIy-0RcK2izxy1dp37MI6VR6OLp3Xg',
    appId: '1:351592381319:ios:22b14366c27fe53649f122',
    messagingSenderId: '351592381319',
    projectId: 'realtime-database-crud-4b68b',
    databaseURL: 'https://realtime-database-crud-4b68b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-crud-4b68b.appspot.com',
    iosBundleId: 'com.example.firebaseRealdatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArf55bu0vRSMIBbpn5J8fQWMav-9SFh9U',
    appId: '1:351592381319:web:2a6a27948eb3e14f49f122',
    messagingSenderId: '351592381319',
    projectId: 'realtime-database-crud-4b68b',
    authDomain: 'realtime-database-crud-4b68b.firebaseapp.com',
    databaseURL: 'https://realtime-database-crud-4b68b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-crud-4b68b.appspot.com',
    measurementId: 'G-EENMESWCMM',
  );
}
